// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA547tFZY3Qs4YFRXUFZgWux1GFJHcAD8E',
    appId: '1:218836573790:web:377389e334dffdfbfcdecf',
    messagingSenderId: '218836573790',
    projectId: 'chat-gpt-200a4',
    authDomain: 'chat-gpt-200a4.firebaseapp.com',
    storageBucket: 'chat-gpt-200a4.appspot.com',
    measurementId: 'G-P4VED7LM41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2Fi80Q-6ww50RFpki3gZsUPIki40bL2Q',
    appId: '1:218836573790:android:6b081b1f03a52c47fcdecf',
    messagingSenderId: '218836573790',
    projectId: 'chat-gpt-200a4',
    storageBucket: 'chat-gpt-200a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8GwCCJfyRuE7RiJhAaLmDKjDN1WkmzyY',
    appId: '1:218836573790:ios:ff1cc7b9d9fdd10dfcdecf',
    messagingSenderId: '218836573790',
    projectId: 'chat-gpt-200a4',
    storageBucket: 'chat-gpt-200a4.appspot.com',
    iosBundleId: 'com.example.chatGptAppUpdated',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8GwCCJfyRuE7RiJhAaLmDKjDN1WkmzyY',
    appId: '1:218836573790:ios:ff1cc7b9d9fdd10dfcdecf',
    messagingSenderId: '218836573790',
    projectId: 'chat-gpt-200a4',
    storageBucket: 'chat-gpt-200a4.appspot.com',
    iosBundleId: 'com.example.chatGptAppUpdated',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA547tFZY3Qs4YFRXUFZgWux1GFJHcAD8E',
    appId: '1:218836573790:web:377389e334dffdfbfcdecf',
    messagingSenderId: '218836573790',
    projectId: 'chat-gpt-200a4',
    authDomain: 'chat-gpt-200a4.firebaseapp.com',
    storageBucket: 'chat-gpt-200a4.appspot.com',
    measurementId: 'G-P4VED7LM41',
  );

}